[package]
name = "server-setup"
version = "0.1.1"
authors = ["Omar Jair Purata Funes <omarpurataf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "*"
scanln = "*"
cmd_lib = "*"
